name: valuemate
description: "A new Flutter project."


version: 3.0.6+6

environment:
  sdk: ^3.6.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_mobx: ^2.3.0
  fluttertoast: ^8.2.12
  get: ^4.7.2
  http: ^1.3.0 
  nb_utils: ^7.0.7
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  motion_tab_bar: ^2.0.4
  water_drop_nav_bar: ^2.2.0
  curved_navigation_bar: ^1.0.3
  carousel_slider: ^5.0.0
  image_picker: ^1.0.4
  file_picker: ^8.0.0+1
  salomon_bottom_bar: ^3.3.2
  shimmer: ^3.0.0
  flutter_launcher_icons: ^0.13.1 # use latest version
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.2
  flutter_html: ^3.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_svg: ^2.2.0






dev_dependencies:

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  
  # Android specific
  adaptive_icon_foreground: "assets/images/app_icon.png"
  adaptive_icon_background: "#00000000"  # Fully transparent
  remove_alpha_android: false  # Preserve transparency
  
  # iOS specific
  remove_alpha_ios: false  # Preserve transparency
  ios_remove_alpha_foreground: false
  


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/
    - assets/flag/
    - assets/images/
    - assets/icons/upi_payment/
    - assets/lottie/
    - assets/newDashboard/
    - assets/json/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
